version: '3.3'

services:
  db:
    # image: postgres
    build:
      dockerfile: Dockerfile
      context: ./Projects/Postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    networks:
      - dock2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      dockerfile: Dockerfile
      context: ./Projects/Django
    # image: javierpipa/django:latest
    restart: always
    profiles: ["frontend"]
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    networks:
      - dock2

networks:
  dock2:

volumes:
  data:
    driver: local
