version: '3.9'

services:
  db:
    # image: postgres
    build:
      dockerfile: Dockerfile
      context: ./Projects/Postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${MI_POSTGRES_DB}
      - POSTGRES_USER=${MI_POSTGRES_USER}
    networks:
      - dock2
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          memory: 20M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      dockerfile: Dockerfile
      context: ./Projects/Django
    # image: javierpipa/django:latest
    restart: always
    profiles: ["frontend"]
    command: python manage.py runserver 0.0.0.0:8000
    deploy:
      resources:
        limits:
          memory: 80M
          cpus: '0.50'
        reservations:
          memory: 20M
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dock2

networks:
  dock2:

volumes:
  data:
    driver: local
